require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Firestore'

target 'SpaceJump' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'SpaceJumpTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SpaceJump-tvOS' do
  # Pods for SpaceJump-tvOS

  target 'SpaceJump-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
